"""
Caterpillar Mini Hydraulic Excavator inspection checklist. VLM output must
map to one of these labels; anything else gets normalized to "Overall machine".
"""
from __future__ import annotations

CHECKLIST_ITEMS: list[str] = [
    # Exterior / walkaround
    "Bucket/GET",
    "Bucket cylinder & linkage",
    "Stick, cylinder",
    "Boom, cylinders",
    "Underneath of machine",
    "Final drive leaks/swing drive leaks area",
    "Carbody",
    "Camera",
    "Undercarriage",
    "Steps & handholds",
    "Batteries & hold downs",
    "Windshield wipers & washers",
    "Fire extinguisher",
    "Engine coolant",
    "Primary fuel filter",
    "Air filter",
    "Hydraulic oil tank",
    "Hydraulic pilot oil filter",
    "Radiator",
    "Hydraulic oil cooler",
    "AC condenser",
    "Lights",
    "Mirrors",
    "Engine oil filter",
    "Hydraulic oil filters",
    "Overall machine",
    # Engine compartment or platforms
    "Engine oil",
    "Swing gear oil",
    "Fuel tank",
    "All hoses",
    "All belts",
    "Overall engine compartment",
    # Inside the cab
    "Seat",
    "Seat belt & mounting",
    "Horn/travel alarm/lights",
    "Indicators",
    "Monitor panel",
    "Switches",
    "Travel controls",
    "Mirrors",
    "Heating system",
    "ROPS",
    "Cooling system",
    "Overall cab interior",
]

CHECKLIST_SET: frozenset[str] = frozenset(CHECKLIST_ITEMS)

# Section headers and item ordering per Caterpillar form "EN_Mini_HEX_Safety & Maint. Inspection"
FROM_GROUND: list[str] = [
    "Bucket/GET",
    "Bucket cylinder & linkage",
    "Stick, cylinder",
    "Boom, cylinders",
    "Underneath of machine",
    "Final drive leaks/swing drive leaks area",
    "Carbody",
    "Camera",
    "Undercarriage",
    "Steps & handholds",
    "Batteries & hold downs",
    "Windshield wipers & washers",
    "Fire extinguisher",
    "Engine coolant",
    "Primary fuel filter",
    "Air filter",
    "Hydraulic oil tank",
    "Hydraulic pilot oil filter",
    "Radiator",
    "Hydraulic oil cooler",
    "AC condenser",
    "Lights",
    "Mirrors",
    "Engine oil filter",
    "Hydraulic oil filters",
    "Overall machine",
]
ENGINE_COMPARTMENT: list[str] = [
    "Engine oil",
    "Swing gear oil",
    "Fuel tank",
    "All hoses",
    "All belts",
    "Overall engine compartment",
]
INSIDE_CAB: list[str] = [
    "Seat",
    "Seat belt & mounting",
    "Horn/travel alarm/lights",
    "Indicators",
    "Monitor panel",
    "Switches",
    "Travel controls",
    "Mirrors",
    "Heating system",
    "ROPS",
    "Cooling system",
    "Overall cab interior",
]

# "What are you looking for?" per Caterpillar form
WHAT_TO_LOOK_FOR: dict[str, str] = {
    "Bucket/GET": "Excessive wear or damage, cracks",
    "Bucket cylinder & linkage": "Excessive wear, damage, leaks, lubricate",
    "Stick, cylinder": "Wear, damage, leaks, lubricate",
    "Boom, cylinders": "Wear, damage, leaks, lubricate",
    "Underneath of machine": "Final drive leaks, swing drive leaks, damage",
    "Final drive leaks/swing drive leaks area": "Final drive leaks, swing drive leaks, damage",
    "Carbody": "Cracks, damage",
    "Camera": "Condition & function",
    "Undercarriage": "Wear, damage, tension",
    "Steps & handholds": "Condition & cleanliness",
    "Batteries & hold downs": "Cleanliness, loose bolts & nuts",
    "Windshield wipers & washers": "Wear, damage, fluid level",
    "Fire extinguisher": "Charge, damage, date of inspection",
    "Engine coolant": "Fluid level",
    "Primary fuel filter": "Leaks, drain water separator",
    "Air filter": "Restriction indicator",
    "Hydraulic oil tank": "Fluid level, damage, leaks",
    "Hydraulic pilot oil filter": "Leaks",
    "Radiator": "Fin blockage, leaks",
    "Hydraulic oil cooler": "Fin blockage, leaks",
    "AC condenser": "Fin blockage, leaks",
    "Lights": "Damage",
    "Mirrors": "Damage, proper adjustment, cleanliness",
    "Engine oil filter": "Leaks",
    "Hydraulic oil filters": "Leaks",
    "Overall machine": "Loose or missing nuts & bolts, loose guards, cleanliness",
    "Engine oil": "Fluid level",
    "Swing gear oil": "Fluid level, leaks",
    "Fuel tank": "Fuel level, damage, leaks",
    "All hoses": "Cracks, wear spots, leaks",
    "All belts": "Tightness, wear, cracks",
    "Overall engine compartment": "Trash or dirt buildup, leaks",
    "Seat": "Adjustment, able to reach pedals",
    "Seat belt & mounting": "Damage, wear, adjustment, installed date, age",
    "Horn/travel alarm/lights": "Proper function",
    "Indicators": "Proper function",
    "Monitor panel": "Proper function",
    "Switches": "Proper function",
    "Travel controls": "Correct operation",
    "Heating system": "Proper function",
    "ROPS": "Damage, loose mounting bolts",
    "Cooling system": "Proper function",
    "Overall cab interior": "Cleanliness",
}
